version: '3.5'
services:
  db-client:
    image: db-client-base:latest
    depends_on:
      - db-server
  db-server:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass

